// Code generated by MockGen. DO NOT EDIT.
// Source: ../symmetrickey.go

// Package mocks_awskms is a generated GoMock package.
package mocks_awskms

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSymmetricKey is a mock of SymmetricKey interface.
type MockSymmetricKey struct {
	ctrl     *gomock.Controller
	recorder *MockSymmetricKeyMockRecorder
}

// MockSymmetricKeyMockRecorder is the mock recorder for MockSymmetricKey.
type MockSymmetricKeyMockRecorder struct {
	mock *MockSymmetricKey
}

// NewMockSymmetricKey creates a new mock instance.
func NewMockSymmetricKey(ctrl *gomock.Controller) *MockSymmetricKey {
	mock := &MockSymmetricKey{ctrl: ctrl}
	mock.recorder = &MockSymmetricKeyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSymmetricKey) EXPECT() *MockSymmetricKeyMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockSymmetricKey) Decrypt() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt")
	ret0, _ := ret[0].(error)
	return ret0
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockSymmetricKeyMockRecorder) Decrypt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockSymmetricKey)(nil).Decrypt))
}

// Encrypt mocks base method.
func (m *MockSymmetricKey) Encrypt() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt")
	ret0, _ := ret[0].(error)
	return ret0
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockSymmetricKeyMockRecorder) Encrypt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockSymmetricKey)(nil).Encrypt))
}

// Generate mocks base method.
func (m *MockSymmetricKey) Generate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockSymmetricKeyMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockSymmetricKey)(nil).Generate))
}

// GetEncryptedKey mocks base method.
func (m *MockSymmetricKey) GetEncryptedKey() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptedKey")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetEncryptedKey indicates an expected call of GetEncryptedKey.
func (mr *MockSymmetricKeyMockRecorder) GetEncryptedKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptedKey", reflect.TypeOf((*MockSymmetricKey)(nil).GetEncryptedKey))
}

// GetEncryptedKeyLen mocks base method.
func (m *MockSymmetricKey) GetEncryptedKeyLen() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptedKeyLen")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetEncryptedKeyLen indicates an expected call of GetEncryptedKeyLen.
func (mr *MockSymmetricKeyMockRecorder) GetEncryptedKeyLen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptedKeyLen", reflect.TypeOf((*MockSymmetricKey)(nil).GetEncryptedKeyLen))
}

// GetKey mocks base method.
func (m *MockSymmetricKey) GetKey() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetKey indicates an expected call of GetKey.
func (mr *MockSymmetricKeyMockRecorder) GetKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockSymmetricKey)(nil).GetKey))
}

// GetKeyID mocks base method.
func (m *MockSymmetricKey) GetKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetKeyID indicates an expected call of GetKeyID.
func (mr *MockSymmetricKeyMockRecorder) GetKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyID", reflect.TypeOf((*MockSymmetricKey)(nil).GetKeyID))
}

// GetKeyLen mocks base method.
func (m *MockSymmetricKey) GetKeyLen() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyLen")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetKeyLen indicates an expected call of GetKeyLen.
func (mr *MockSymmetricKeyMockRecorder) GetKeyLen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyLen", reflect.TypeOf((*MockSymmetricKey)(nil).GetKeyLen))
}

// SetEncryptedKey mocks base method.
func (m *MockSymmetricKey) SetEncryptedKey(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEncryptedKey", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEncryptedKey indicates an expected call of SetEncryptedKey.
func (mr *MockSymmetricKeyMockRecorder) SetEncryptedKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEncryptedKey", reflect.TypeOf((*MockSymmetricKey)(nil).SetEncryptedKey), arg0)
}

// SetKey mocks base method.
func (m *MockSymmetricKey) SetKey(arg0 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKey", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKey indicates an expected call of SetKey.
func (mr *MockSymmetricKeyMockRecorder) SetKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKey", reflect.TypeOf((*MockSymmetricKey)(nil).SetKey), arg0)
}
